name: Proxy Scanner Nautica

on:
  workflow_dispatch:
  

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Start Scan
        run: |
          bun install && bun run ./scan-nautica/main.ts
      - name: Publish Result
        if: ${{ success() }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m " 🔄 Update proxyip"
          git push origin main --force
